// enum

// unless defined, the value is incremental
// use const to limit the JS code being generated by tsc enum.ts
const enum PaymentType {
  COD = 67,
  Paid,
  Installment = 89,
}

const selectedPayment = PaymentType.COD;
// value is 0
console.log(selectedPayment);

interface SomeProps {
  name: "";
  age: 0;
}
